
//------------------------------------------------------------------------------
// FileName = C:\Users\r.porter\Source\Repos\o365ApiTester\App.config
// Generated at 01/29/2016 17:43:54
//
/// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//    NOTE: Please use the Add a Reference to System.Configuration assembly if 
//          you get compile errors with ConfigurationManager
//
/// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Configuration;

namespace o365ApiTester
{
   /// <remarks>
   /// You can create partial class with the same name in another file to add custom properties
   /// </remarks>
   public static partial class SiteSettings
   {
      /// <summary>
      /// Static constructor to initialize properties
      /// </summary>
      static SiteSettings()
      {
         var settings = System.Configuration.ConfigurationManager.AppSettings;
         ida_ClientId = settings[ "ida_ClientId" ];
         ida_AADInstance = settings[ "ida_AADInstance" ];
         ida_Domain = settings[ "ida_Domain" ];
         oneDriveApiEndpoint = settings[ "oneDriveApiEndpoint" ];
         graphResourceId = settings[ "graphResourceId" ];
         graphApiEndpoint = settings[ "graphApiEndpoint" ];
         redirectUrl = settings[ "redirectUrl" ];
      }

      /// <summary>
      /// ida_ClientId configuration value
      /// </summary>
      public static readonly string ida_ClientId;

      /// <summary>
      /// ida_AADInstance configuration value
      /// </summary>
      public static readonly string ida_AADInstance;

      /// <summary>
      /// ida_Domain configuration value
      /// </summary>
      public static readonly string ida_Domain;

      /// <summary>
      /// oneDriveApiEndpoint configuration value
      /// </summary>
      public static readonly string oneDriveApiEndpoint;

      /// <summary>
      /// graphResourceId configuration value
      /// </summary>
      public static readonly string graphResourceId;

      /// <summary>
      /// graphApiEndpoint configuration value
      /// </summary>
      public static readonly string graphApiEndpoint;

      /// <summary>
      /// redirectUrl configuration value
      /// </summary>
      public static readonly string redirectUrl;

   }
}

